### ISSUE TITLE
Specify Branch

### ISSUE THREAD

**Issue by afk-mario** [openupm/openupm-cli#11]
Is there any way I can specify the branch I want to use ? tried

`openupm add dev.yarnspinner.unity@git@github.com:YarnSpinnerTool/YarnSpinner-Unity.git#develop`
with no success

**Comment by favoyang** [comment]
It seems a bug of UPM itself, that specifying version (branch or commit hash) with SSH protocol is not supported.

But https protocol supports it.

```
openupm add dev.yarnspinner.unity@https://github.com/YarnSpinnerTool/YarnSpinner-Unity.git#develop
```

Refs https://docs.unity3d.com/Manual/upm-git.html

**Comment by afk-mario** [comment]
@favoyang Thanks !
