### ISSUE TITLE
Do not create scopedRegistry when scopes are empty

### ISSUE THREAD

**Issue by nowsprinting** [openupm/openupm-cli#134]
I am running the following command for automated testing of my UPM packages.
```
openupm -c $(PROJECT_HOME) add -ft MY_PACKAGE_NAME@file:../../
```

Created manifest.json is:
```
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": []
    }
  ],
  "testables": [
    "MY_PACKAGE_NAME"
  ]
```

An error occurred when opening this project:
```
[Package Manager] Registry configuration is invalid:
  Scoped registry at position 1 is invalid:
    "scopedRegistries[0].scopes" must contain at least 1 items
[Package Manager] Failed to update project manifest: Registry configuration is invalid:
  Scoped registry at position 1 is invalid:
    "scopedRegistries[0].scopes" must contain at least 1 items
```

This issue occurs in v1.19.6. The manifest.json at v1.17.0 was as follows:
```
  "scopedRegistries": [
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.openupm"
      ]
    }
  ],
  "testables": [
    "MY_PACKAGE_NAME"
  ]
```

In v1.17.0, scopes existed, so there was no problem.

**Comment by ComradeVanti** [comment]
Hm interesting. Yes, it used to be that a `com.openupm` scope would always be added, which avoided this issue. I guess the solution is to either add a "dummy scope" like that again, or to not add a scoped registry at all if not necessary. What do you think @favoyang?

**Comment by favoyang** [comment]
In this case, the scope registry 'package.openupm.com" should not be added to the `manifest.json`.
