### ISSUE TITLE
Bug: openupm search seems to be broken

### ISSUE THREAD

**Issue by favoyang** [openupm/openupm-cli#2]
e:\Archive\Prgdir\Svelto\Svelto.MiniExamples\Example6>e:\node-v12.14.0-win-x64\openupm search com.sebaslab.svelto.ecs
fast search endpoint is not available, using old search.
(node:1424) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '\Users\Seb-e-Sam.openupm'
at Object.mkdirSync (fs.js:823:3)
at getCache (e:\node-v12.14.0-win-x64\node_modules\openupm-cli\lib\core.js:224:8)
at searchOld (e:\node-v12.14.0-win-x64\node_modules\openupm-cli\lib\cmd-search.js:38:15)
at module.exports (e:\node-v12.14.0-win-x64\node_modules\openupm-cli\lib\cmd-search.js:113:34)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Command. (e:\node-v12.14.0-win-x64\node_modules\openupm-cli\lib\cli.js:53:21)
(node:1424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by favoyang** [comment]
@sebas77, could you please provide me more informations?

- openupm-cli version: `openupm --version`
- If it's not the latest version could try to upgrade to the latest version? `npm install -g openupm-cli`. Then try again?
- What's your terminal? CMD?

**Comment by sebas77** [comment]
OpenUPM version is 1.5.1. the terminal is CMD

**Comment by favoyang** [comment]
@sebas77 the problem is related to the way to detect home directory. Could you please try the latest 1.5.2 version?

```
npm install -g openupm-cli
```

**Comment by sebas77** [comment]
I probably won't test it until my next release. If you fixed it with 1.5.2 you can consider it closed. I did a npm install -g openupm-cli before to test it and at that time 1.5.2 wasn't available yet.

**Comment by favoyang** [comment]
@sebas77 I cannot reproduce it with previous version using terminal CMD. But from the error log, I suspect it related to the way to detect the home directory, and try to fix with version 1.5.2. And the 1.5.2 is published after the error report.

I'll close this for now, but feel free to comment if the search of version 1.5.2 is still not working for you.
