### ISSUE TITLE
Next Unity crap

### ISSUE THREAD

**Issue by Razenpok** [openupm/openupm-cli#25]
Hi Favo,

Looks like Unity's making things harder again.

https://forum.unity.com/threads/updates-to-our-terms-of-service-and-new-package-guidelines.999940/#post-7158721

> Would a standalone package manager, external to the Unity editor, be okay?
> 
> No. The Package Guidelines state: "You [cannot] add, update or modify installed Packages on behalf of the user outside the official Unity Editor UI, such as programmatically through scripts."

Do you think this is relevant to OpenUPM CLI?

**Comment by favoyang** [comment]
Hi @Razenpok,

Thank you for taking care of us. OpenUPM-CLI is just a helper script to modify the `manifest.json` for you. It won't download the tarball, extract it to the Unity project folder directly. In another word, it won't try to act as an alternative solution to the PackMan. I think both OpenUPM and OpenUPM-CLI are survived in the Unity ecosystem.

**Comment by Razenpok** [comment]
Cool, thanks for the answer!
