### ISSUE TITLE
tool modified whitespace of manifest and package-lock.json

### ISSUE THREAD

**Issue by StephenHodgson** [openupm/openupm-cli#388]
It'd be nice if the cli tool didn't modify the whitespace characters of the manifest.json and package-lock.json files.

**Comment by ComradeVanti** [comment]
We dont touch the `package-json.lock` file, so if something changes there, it must be Unity itself doing it.

Could you give some examples what whitespace characters in the manifest change unexpectedly?

**Comment by StephenHodgson** [comment]
Sorry false positive. Was able to track it down to unrelated thing. Thanks for the tool it is awesome!
