### ISSUE TITLE
bug: OpenUPM CLI tool is no longer installing dependencies

### ISSUE THREAD

**Issue by SimonDarksideJ** [openupm/openupm-cli#392]
We updated a package due to what we perceived as an error in the package, we checked all the settings and the package.json, which were all good.

However, on installing a package with dependencies to another package on OpenUPM, the dependencies are NOT installed.

## Replication Steps

1. Examine the package.json in the following package

  https://github.com/realitycollective/com.realitycollective.service-framework

2. It's dependencies include 2 Unity packages and 1 OpenUPM package, namely

  [com.realitycollective.utilities@1.0.13](https://openupm.com/packages/com.realitycollective.utilities/)
 
## What is expected to happen

In previous releases, dependencies recognized by the tool as OpenUPM packages were also installed alongside the package, including scope

## What is actually happening

The named package is installed, however, the dependencies are NOT.

**Comment by favoyang** [comment]
Indeed, `openupm install com.realitycollective.service-framework` only installed `com.realitycollective.service-framework` itself, missing the `com.realitycollective.utilities` in the scope field.

Tested with openupm-cli 4.1.1

**Comment by favoyang** [comment]
The bug was introduced in v3.4.0 (https://github.com/openupm/openupm-cli/compare/3.3.1...3.4.0)

Please roll back to v3.3.1 before we fix it.

```
npm install openupm-cli@3.3.1 -g
```

**Comment by SimonDarksideJ** [comment]
Thanks. It's more of a general issue for users of the CLI tool than for us as package providers.

**Comment by favoyang** [comment]
Thanks, I'm aware of this general issue.

**Comment by ComradeVanti** [comment]
@SimonDarksideJ thanks for reporting. I'll take a look now.

**Comment by ComradeVanti** [comment]
The issue comes from an error in the dependency-graph resolving logic where we stopped recursively resolving once a built-in package was encountered. Since the above package depends first on `com.unity.ugui` the dependency graph logic stops the resolve process before coming to the next package. This is a mistake, it should continue resolving.

**Comment by ComradeVanti** [comment]
Should be fixed now. Can you confirm @SimonDarksideJ?

**Comment by SimonDarksideJ** [comment]
Thanks, will check that out asap

**Comment by ComradeVanti** [comment]
I'll assume it works. Please open a new issue if not.

**Comment by SimonDarksideJ** [comment]
Apologies, meant to send a note and close the issue.

Yes, confirmed the issue is resolved in 4.1.2. 

I really appreciate the team's efforts on resolving this quickly!
