### ISSUE TITLE
Search Endpoint Down (502 Bad Gateway)

### ISSUE THREAD

**Issue by Zulu-Inuoe** [openupm/openupm-cli#43]
Hey all,
Please direct me elsewhere if I'm posting this (an outage problem) in the wrong place.

In Unity I got the following error while listing packages:

[Package Manager Window] Cannot perform upm operation: Unable to perform online search:
  Request [GET https://package.openupm.com/-/v1/search?text=com.openupm&from=0&size=250] failed with status code [502] [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

I tried using the openupm-cli with search and received the following output:
```
λ npx openupm-cli search ui
ERR! 502 Bad Gateway - GET https://package.openupm.com/-/v1/search?text=ui&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5
WARN fast search endpoint is not available, using old search.
┌──────────────────────────────────────────┬────────────────────┬────────────┐
│ Name                                     │ Version            │ Date       │
├──────────────────────────────────────────┼────────────────────┼────────────┤
│ org.nuget.quikgraph                      │ 2.5.0              │            │
├──────────────────────────────────────────┼────────────────────┼────────────┤
```
..it continues to list additional results correctly but notice the immediate 502 failure on the second line.

So it looks like some backend service might be down?

**Comment by favoyang** [comment]
@Zulu-Inuoe thx for reporting the issue. The server is highly unstable for 5h. Please see more details on the discord discussion: https://discord.com/invite/FnUgWEP. I will post more info there. For now, it's self-fixed.

**Comment by favoyang** [comment]
@all-contributors please add @Zulu-Inuoe for bug.
