### ISSUE TITLE
Discussion: Split up core module

### ISSUE THREAD

**Issue by ComradeVanti** [openupm/openupm-cli#57]
The `core.ts` module is pretty big and contains a variety of different common functionality. I would propose splitting this module into multiple smaller ones dedicated to specific data-types or workflows.

This way related code is kept together which makes it easier to find it.

This does not introduce any new functionality, but hopefully makes it easier to add new stuff in the future.

While [converting the project to typescript](https://github.com/openupm/openupm-cli/pull/52) I already did this for some functions such as `splitPkgName` which moved from core to [a module for all functions related to package-names](https://github.com/openupm/openupm-cli/blob/8e68b9a9a2a1956cdc482ddad90523e4752a8b03/src/utils/pkg-name.ts).

Thoughts?

**Comment by favoyang** [comment]
Sounds good to me.
